#!/usr/bin/env bash

# Ansi escape sequences of all terminal colors
# Scripts can source this file to colorize output

shopt -s xpg_echo

# .-------------------------------------------.
# |   Color       | Foreground  | Background  |
# +-------------------------------------------+
# Black           |      30     |     40      |
# Red             |      31     |     41      |
# Green           |      32     |     42      |
# Yellow          |      33     |     43      |
# Blue            |      34     |     44      |
# Magenta         |      35     |     45      |
# Cyan            |      36     |     46      |
# White           |      37     |     47      |
# Bright Black    |      90     |    100      |
# Bright Red      |      91     |    101      |
# Bright Green    |      92     |    102      |
# Bright Yellow   |      93     |    103      |
# Bright Blue     |      94     |    104      |
# Bright Magenta  |      95     |    105      |
# Bright Cyan     |      96     |    106      |
# Bright White    |      97     |    107      |
#
# +-----------------------------------+
# |          Text Attributes          |
# +-----------------------------------+
# |  Attribute    |   Value           |
# +-----------------------------------+
# |  Noramal      |     0             |
# |  Bold         |     1             |
# |  Faint        |     2             |
# |  Italic       |     3             |
# |  underline    |     4             |
# |  Blink        |     5 (no effect) |
# |  Reverse      |     7             |
# |  Invisible    |     8             |
# |  Normal(2)    |    22             |
# |  No Italic    |    23             |
# |  No Underline |    24             |
# |  No Blink     |    25 (no effect) |
# |  No Reverse   |    27             |
# +-----------------------------------+

    nrm=$'\e[0m';        bld=$'\e[1m'
    fnt=$'\e[2m';       ital=$'\e[3m'
    undl=$'\e[4m';      blnk=$'\e[5m'
    rvs=$'\e[7m';        inv=$'\e[8m'
   nrm2=$'\e[22m';   no_ital=$'\e[23m'
no_undl=$'\e[24m';  no_blink=$'\e[25m'
 no_rvs=$'\e[27m'

# +------------------------------+
# |   Normal Foreground Colors   |
# +------------------------------+
blk=$'\e[30m'; red=$'\e[31m'
grn=$'\e[32m'; yel=$'\e[33m'
blu=$'\e[34m'; mag=$'\e[35m'
cyn=$'\e[36m'; wht=$'\e[37m'
def=$'\e[39m'

# +--------------------------------+
# |    Bright Foreground Colors    |
# +--------------------------------+
Bblk=$'\e[90m'; Bred=$'\e[91m';
Bgrn=$'\e[92m'; Byel=$'\e[93m';
Bblu=$'\e[94m'; Bmag=$'\e[95m';
Bcyn=$'\e[96m'; Bwht=$'\e[97m'

# +--------------------------------+
# |    Normal Background Colors    |
# +--------------------------------+
_blk=$'\e[40m'; _red=$'\e[41m';
_grn=$'\e[42m'; _yel=$'\e[43m';
_blu=$'\e[44m'; _mag=$'\e[45m';
_cyn=$'\e[46m'; _wht=$'\e[47m'

# +--------------------------------+
# |    Bright Background Colors    |
# +--------------------------------+
_Bblk=$'\e[100m'; _Bred=$'\e[101m';
_Bgrn=$'\e[102m'; _Byel=$'\e[103m';
_Bblu=$'\e[104m'; _Bmag=$'\e[105m';
_Bcyn=$'\e[106m'; _Bwht=$'\e[107m'
