#!/usr/bin/env bash

#
# This will symlink the files in this repo to ~ as "dotfiles".
#
# Existing files are copied to a save directory (~/dotfiles-old) for
# easy rollback if necessary.
#
shopt -s xpg_echo

[[ ! -f ~/.dotfiles-old ]] && mkdir ~/.dotfiles-old

# Date used for saved files
now="$(date +'%Y_%m%d%H%M%S')"

# files symlinked to $HOME

dotfiles=(bash_profile
   bashrc
   colors
   dircolors
   git-completion.sh
   git-prompt.sh
   gitflow_export
   gitignore_global
   vimrc
)

for dotfile in "${dotfiles[@]}"
do
    if [[ -f ~/.${dotfile} ]]
    then
        echo "Moving ~/.${dotfile} to ~/.dotfiles-old/${dotfile}-${now}"
        mv ~/.${dotfile} ~/.dotfiles-old/${dotfile}-${now}
    fi
    ln -sf $(pwd)/$dotfile $HOME/.${dotfile}\n
done
